travis:
  secure:
    BINSTAR_TOKEN: hu8GPz4D3ebieL6p9iYUoY1+AxM4vjicPwkSkYLv5tamv6lc2dUpTche5JQxks79WgSCmgK6BkVAgxBgJoSOBuXMOm792LuW2hLWXJ1RvGwxGCAbhPpcVKQenQMkGOZgz3194DDat/ATVMEs0xSHA8UXQZ3Z6EcCYBfr6ZMF4RLLuoROrJo5HC//i4lyCdUfTB1ADM5P6NJgznAIzr15qsH+oE9ZXH9SzdKUs3Yz5l+f8yoKP+l7k2AWpiCu+WvwoJtGBnDVEZxYW55/KTq/f4ndHKYIdhCd+bwe5vTz9drPNIDmLxEjfgUgPAK0VnkFJFnlbjLwPTL4gNAyEvT8Wqf3DFMNeXk3TE0DiPs4945g6c9EQAo8vTLipLP4l9zhRORMipQW7Zxa3wHDiqO0QCLiTaiwPsCuL5By6njE75rnTJJeCILeKhpnYsIOnV4R4aoMdIPc1LkxrIF+Kz0NTRKH71mrzIY/pcjBvWU0J482u32T3yNHzaC4utwYxu/hPdC/bIF3poOk02b82XOnkqIBSw4ESDN7DlVJVOftZb4Y5WGsWhXGc9fMV9VMNvn3pVh9Oihbn6mJ44ayrTPy9iu1iapAFn/+6V33l62fwxtl5qGuXZnzRepPh6ExAXbIoqk4jC5UYtT9U7Bsl844BaJR9bu2yv7AVt9O0/KfF14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
